### ISSUE TITLE
include json file in annotations - Blueprint

### ISSUE THREAD

**Issue by kadinho** [dingo/api#654]
Hello,

sorry open a issue for this but it really helps, i wanna include a file with a json response in the body. It's possible ?

example:

@Response(200, body={"name" : "foo",}) ----> @Response(200, body= include(filename))

thx

CV

**Comment by jasonlewis** [comment]
Hm, that's an interesting one... It's not possible, but it could be interesting.

You want to do this because including a sample response body is too big for this particular response?

**Comment by smartfin** [comment]
Is it possible to read the file and then return response with read data?

**Comment by marijang** [comment]
+1

**Comment by marijang** [comment]
it will be cool to have something like this
@partial(path\filename.md)

So we can separate documentation from controller code
What do you think?

**Comment by marsd** [comment]
+1 
Currently encountering reponse data that is too big (+50 lines when exploded) to put into the controller

**Comment by jasonlewis** [comment]
I'm tempted on this idea guys. Will put it into the 1.0.0 milestone and see how I go when I get back from holidays.

**Comment by realshadow** [comment]
@jasonlewis Hey, did you get anywhere with this feature? I could really use this :)

**Comment by jasonlewis** [comment]
I've just implemented this on both here and the Blueprint repository.

To use it, you simply provide a string body for either a request or a response, but prefix the string with either `json:` or `file:`, then provide a path relative to the base directory.

Example:

```php
/**
 * @Response(200, "json:docs/response/example")
 */
```

If you use `json:` then you don't need to worry about a `.json` file extension. If your files are not using a `.json` extension then use the `file:` prefix and provide the extension.

When using the command there's a new `--include-path` option which you can use to configure a base path relative to the root directory. So, for example, your docs are stored at `{root}/docs`, but you don't want to write `docs/response/example` every time.

So when you call the command you would use `--include-path "docs"`, your annotation would then look like this:

```php
/**
 * @Response(200, "json:response/example")
 */
```

Let me know if you'd prefer the `--include-path` option to not default to being relative to the root directory.

**Comment by shwhl** [comment]
@jasonlewis Can you make the support for `json:` and `file:` global? So that we can use this in more cases.
```
@Request({"username": "foo", "password": "bar"}, headers="json:header/authorization")
```

**Comment by shwhl** [comment]
An error occurred dingo/blueprint#35

**Comment by rajathans** [comment]
what happened to this feature i cant use --include-path anymore.
Gives me :

>  [Symfony\Component\Console\Exception\RuntimeException]  
>   The "--include-path" option does not exist.

**Comment by hskrasek** [comment]
@rajathans Nothing happened to it, the option still exists. Are you possibly on a version that was before this was added?

**Comment by rajathans** [comment]
@hskrasek i'm using `"dingo/api": "1.0.x@dev"` in my composer file

**Comment by hskrasek** [comment]
@rajathans Trying switching to "dev-master" in your composer file. That should resolve the issue
